### ISSUE TITLE
Error in workflow "DeepL" - 'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by dia-pko** [Skoda091/alfred-deepl#7]
**Steps to reproduce:**
- Open Alfred
- Type "EN Hallo" 

**Expected:**
Input was translated and copied to clipboard. 

**Actual:** 
Error message is displayed:
Error in workflow "DeepL" 
'NoneType' object has no attribute 'info'
<img width="560" alt="bildschirmfoto 2018-03-29 um 09 36 16" src="https://user-images.githubusercontent.com/467088/38076249-5ec0f124-3335-11e8-990e-edb04496989e.png">

**Comment by xenDE** [comment]
same here with "dl text" :(

OSX 10.11.6 / Python 2.7.14

**Comment by Elindorath** [comment]
Access to the DeepL API is now paid at 20€ / month limited to 1000000 characters. This workflow can no longer work.

**Comment by xenDE** [comment]
my DeepL browser plugins are still working.

for example "Deep Translator 1.0.14" on Chrome

**Comment by dia-pko** [comment]
Is it possible to add my own API key to this workflow?

**Comment by Skoda091** [comment]
Unfortunately, DeepL has restricted access to their API in order to provide paid plans. For now, the workflow can no longer work. @dia-pko When it comes to providing a possibility to add own API key for DeepL paid plans, for now I don't have any plans to add this feature but feel free to contribute and I will be happy to review, merge and publish a new version.

**Comment by AlexanderWillner** [comment]
Quick hack that works: https://github.com/AlexanderWillner/deepl-alfred-workflow2
